---
Name: approutes
After: framework/_config/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'cart': 'CartController'
    'cart/viewCart': 'CartController/viewCart'
    'cart/add': 'CartController/add'
    'cart/remove': 'CartController/remove'